package gratatouille.gradle.tasks

import gratatouille.tasks.GOutputDirectory
import gratatouille.tasks.GTask
import java.io.File
import java.util.*

@GTask
fun generateDescriptor(id: String, implementationClass: String, output: GOutputDirectory) {
  output.resolve("META-INF/gradle-plugins").apply {
    mkdirs()
    resolve("$id.properties").writer().use {
      /**
       * Write a descriptor looking like this:
       *
       * ```
       * #Gradle plugin descriptor (auto-generated by Gratatouille)
       * implementation-class=testplugin.TestPlugin
       * ```
       *
       * Note that we are not using [java.util.Properties] because they
       * write a timestamp that makes builds non-reproducible.
       *
       * TODO: do we need escaping of the plugin class name? I don't expect any exotic character there but maybe?
       */
      it.append("#Gradle plugin descriptor (auto-generated by Gratatouille)\n")
      it.append("implementation-class=$implementationClass\n")
    }
  }
}
