name: Build pull request

on: pull_request

jobs:
  build-pull-request:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
      - uses: gradle/actions/setup-gradle@ac638b010cf58a27ee6c972d7336334ccaf61c96 #v4.4.1
      - run: |
          ./gradlew build
          ./gradlew -p test-plugin build
          ./gradlew -p test-plugin-isolated build
          ./gradlew -p test-app build
