name: Publish release

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  publish-release:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
      - uses: gradle/actions/setup-gradle@ac638b010cf58a27ee6c972d7336334ccaf61c96 #v4.4.1
      - run: |
          LIBRARIAN_RELEASE=true ./gradlew librarianPublishToMavenCentral
        env:
          LIBRARIAN_SONATYPE_PASSWORD: ${{ secrets.CENTRAL_PORTAL_PASSWORD }}
          LIBRARIAN_SONATYPE_USERNAME: ${{ secrets.CENTRAL_PORTAL_USERNAME }}
          LIBRARIAN_SIGNING_PRIVATE_KEY: ${{ secrets.GPG_KEY }}
          LIBRARIAN_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.GPG_KEY_PASSWORD }}
